//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Assignment
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Kategori")]
        public int Categories_ID { get; set; }
        [Display(Name = "Underkategori")]
        public Nullable <int> SubCategories_ID { get; set; }
        [Required]
        [Display(Name = "Typ av uppgift")]
        public string Assignment_Type { get; set; }
        [Display(Name = "Ljudfil")]
        public string Audio_File { get; set; }
        [Display(Name = "Rubrik")]
        public string Assignment_Title { get; set; }
        [Display(Name = "Svarsalternativ 1")]
        public string Answer_One { get; set; }
        [Display(Name = "Svarsalternativ 2")]
        public string Answer_Two { get; set; }
        [Display(Name = "Svarsalternativ 3")]
        public string Answer_Three { get; set; }
        [Display(Name = "Svarsalternativ 4")]
        public string Answer_Four { get; set; }
        [Display(Name = "Svarsalternativ 5")]
        public string Answer_Five { get; set; }
        [Display(Name = "Svarsalternativ 6")]
        public string Answer_Six { get; set; }
        [Required]
        [Display(Name = "Rätt svar")]
        public string Correct_Answer { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
